# Generated by Django 5.0.3 on 2024-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0003_poem_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date_published',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
