# Generated by Django 5.0.3 on 2024-04-13 14:56

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/profile_images/default.png', upload_to=members.models.profile_image_path),
        ),
    ]
